### ISSUE TITLE
Get-SmartCardCred integration with Connect-AzureAD & Connect-MsolService

### ISSUE THREAD

**Issue by jimmy58663** [jimmy58663/pscredentialWithCert#1]
@GeorgeChiuTheHartford I opened the issue here as I do not think the other repo is still being managed.

Thanks for the provided Get-SmartCardCred script block, it works well for on-prem, however, it does not work for Azure or Office 365 cmdlet such as Connect-AzureAD and Connect-MsolService. Does anyone know what's the solution ?

**Comment by jimmy58663** [comment]
@GeorgeChiuTheHartford I am not familiar with either of those commands as I do not have any work with O365 or Azure. If they provide a Credential parameter like most PowerShell cmdlets that need authentication and expect a PSCredential object, they may be handling the UserName incorrectly like Start-Process does. You could try the below which will launch a new PS session as your selected credential and then try to connect up to Azure or O365 without specifying a credential.

```
$Cred = Get-SmartCardCred

$StartInfo = New-Object System.Diagnostics.ProcessStartInfo
$StartInfo.FileName = 'powershell.exe'
$StartInfo.UseShellExecute = $false
$StartInfo.UserName = $Cred.Username
$StartInfo.Password = $Cred.Password
$StartInfo.Arguments = 'Start-Process powershell'
$StartInfo.WorkingDirectory = $env:windir

$Process = New-Object System.Diagnostics.Process
$Process.StartInfo = $StartInfo
$Process.Start()

$Cred = $null
```

**Comment by GeorgeChiuTheHartford** [comment]
Hi @jimmy58663 , Thanks for your reply!   Azure/Office 365 cmdlets do have the -credentails parameter which takes the PSCredential object.   An example is the Connect-AzureAD https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0 , it just does not work.  What would you recommend?  Contact Microsoft support to figure out ?

**Comment by jimmy58663** [comment]
You will have to forgive my lack of knowledge with Azure authentication, but are the credentials on your smart card tied to just Azure or are they credentials to an account on-prem that can also authenticate to Azure?

If it is the second scenario, you can use what I posted above to launch a PowerShell session as the smart card credentials. Those credentials should then be passed by default when you connect to Azure without having to specify otherwise.

**Comment by GeorgeChiuTheHartford** [comment]
@jimmy58663, thanks for your reply again!   It is the 2nd scenario that's how I was able to test the on-prem PowerShell execution successfully.  We have on-prem Active directory synched to cloud Azure AD and use ADFS for both internal/external authentication.   For some reasons, it just does not work with the cloud authentication with PowerShell but works well with Browser.

**Comment by jimmy58663** [comment]
Closing as this seems to be an issue with how the Azure cmdlets handle pscredentials.
