### ISSUE TITLE
Using smartcard credentials to start a process as Admin

### ISSUE THREAD

**Issue by chris6611** [jimmy58663/pscredentialWithCert#3]
.

**Comment by jimmy58663** [comment]
@Christian-Martinez1 I am not sure exactly what is going on with yours. Did you add the `$StartInfo.Verb = 'runas'` in with the rest of the $StartInfo section? In my terminal, both whoami and the administrator role show correctly.

The script does launch a unelevated PowerShell session which launches an elevated PowerShell session afterwards and then the unelevated one closes automatically. Do you have UAC enabled? Are you getting prompted by UAC at all? It should prompt you to select yes to launch the elevated prompt if UAC is enabled.
